### ISSUE TITLE
amanar is missing a license file

### ISSUE THREAD

**Issue by halcyondude** [garetht/amanar#11]
I'm finding amanar quite useful, and would like to contribute.  

Could you please add an open source license?   I want to ensure that when contributing I'm doing things correctly.

From: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

>Note: If you publish your source code in a public repository on GitHub, according to the Terms of Service, other GitHub users have the right to view and fork your repository within the GitHub site. If you have already created a public repository and no longer want users to have access to it, you can make your repository private. When you convert a public repository to a private repository, existing forks or local copies created by other users will still exist. For more information, see "Making a public repository private."

We are currently working in a fork, but have as a specific goal to contribute back to this project.

Thanks!

**Comment by garetht** [comment]
Just added MPL 2.0 as the license.

**Comment by halcyondude** [comment]
awesome thx
